### ISSUE TITLE
如何在控制台隐藏插件自带的 console.log 和 console.info

### ISSUE THREAD

**Issue by zaxlct** [TencentCloud/chat-uikit-vue#29]
这些 console 影响到开发者了

**Comment by Ashster** [comment]
请参考 tim-js-sdk 的 setLogLevel,文档详情：https://web.sdk.qcloud.com/im/doc/zh-cn/SDK.html#setLogLevel
<img width="944" alt="image" src="https://user-images.githubusercontent.com/57951148/229395775-ab66e62a-8353-48db-804a-21218bab07d5.png">
