### ISSUE TITLE
vue2的项目咋集成

### ISSUE THREAD

**Issue by fzlinjianhui** [TencentCloud/chat-uikit-vue#36]
vue2的项目咋集成

**Comment by fzlinjianhui** [comment]
他这个不支持vue2

**Comment by Ashster** [comment]
暂时不支持vue2，vue2版本正在开发中，敬请期待🙇

**Comment by fzlinjianhui** [comment]
加油加油，赶紧出，不然黄花菜都凉了

**Comment by Ashster** [comment]
您好，vue2最新版本已发布！
npm快速集成方案：https://www.npmjs.com/package/@tencentcloud/chat-uikit-vue2
github vue2 demo示例：https://github.com/TencentCloud/chat-uikit-vue/tree/main/Vue2/Demo
欢迎使用
