### ISSUE TITLE
uikit不符合typescript语法规范，无法通过TS类型检查！

### ISSUE THREAD

**Issue by cvpv** [TencentCloud/chat-uikit-vue#37]
![image](https://github.com/TencentCloud/chat-uikit-vue/assets/84720311/b4d877a5-6457-485b-8cf4-4f1ec42c9ead)
上面的截图，来自命令vue-tsc --noEmit -p tsconfig.app.json --composite false 的执行结果
我的ts版本: 5.0.4
项目是完全安装官网步骤创建的新项目，
运行一切正常，就是ts校验爆红，无法编译，如果要打包只能强制去掉type-check，不运行"vue-tsc --noEmit -p tsconfig.app.json --composite false"命令

**Comment by Ashster** [comment]
不好意思，目前版本暂不支持vue-tsc校验，请关闭vue-tsc使用
