### ISSUE TITLE
Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'

### ISSUE THREAD

**Issue by a1056847723** [TencentCloud/chat-uikit-vue#52]
![image](https://github.com/TencentCloud/chat-uikit-vue/assets/50873639/250c33ed-9e5e-4ccc-9b8e-86fe7e2c56da)

**Comment by Ashster** [comment]
您好，请问您是否按照 npm i --legacy-peer-deps进行依赖安装？ 如果是，请检查您的 node 版本是否在14-20这个区间范围内
<img width="762" alt="image" src="https://github.com/TencentCloud/chat-uikit-vue/assets/57951148/15400f69-2697-4ee3-a144-bb3a47ee6d0a">
