### ISSUE TITLE
不支持使用JS吗？

### ISSUE THREAD

**Issue by lexoops** [TencentCloud/chat-uikit-vue#69]
![1713166849266](https://github.com/TencentCloud/chat-uikit-vue/assets/33716494/1f63eb2e-b743-4e8e-9816-ef7087e6027a)
![image](https://github.com/TencentCloud/chat-uikit-vue/assets/33716494/7f03d538-cb75-4f31-9151-084c6b58e3b4)

**Comment by Ashster** [comment]
您好，支持js。您这个报错看起来是
