### ISSUE TITLE
如何监听历史消息（例如5分钟内的任意一条）被撤回

### ISSUE THREAD

**Issue by qidian99** [TencentCloud/chat-uikit-vue#78]
chat-uikit-engine 无法查看源码

目前使用 vue3 sdk，监听 message list，每次都要全量遍历判断是否撤回。

请问在哪里查看所有的监听事件list，CONV/CHAT/CUSTOM

**Comment by Ashster** [comment]
您好，相关接口/事件文档请查看 https://web.sdk.qcloud.com/im/doc/chat-engine/global.html#StoreName
